ktor:
  application:
    modules:
      - com.taskconvertai.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/analyzer"
  user: "analyzer_user"
  password: "analyzer_pass"
ai:
  baseUrl: "http://localhost:8000"
  requestTimeoutMs: 1500000 # 25 минут
